name: Build and deploy page

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-page:
    name: Build Home page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up project
        uses: ./.github/actions/setup-node-deps

      - name: Build project
        run: pnpm run build

      - name: Setup AWS <-> GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: deploy-homepage-session

      - name: Deploy with CDK
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          cd infra
          pnpm run cdk:deploy
